### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by nneal** [bebraw/segmentize#2]
Hey just an fyi, we're getting a deploy error because babelify tries to automatically run `test.js` through which depends on `intersect` which isn't installed for prod. I'm guessing the fix would be using a more canonical way of setting up a test directory.

Anyway, I fixed it by moving segmentize into our repo and not using the npm package, but thought id let you know

**Comment by nneal** [comment]
correction: that did not actually fix the error, thought it would. Getting diff one now

`Cannot find module 'segmentize' from '/our_dirs/shared/node_modules/react-pagify/dist-modules'`

**Comment by bebraw** [comment]
Alright. I have a rough fix in mind. I will set up `files` field and include just dist to the published version. I will get that done today. :+1:
