### ISSUE TITLE
Second last `page` does not correctly create `nextPages` array

### ISSUE THREAD

**Issue by mattwaler** [bebraw/segmentize#3]
When using this library, when you are on the second last page, `nextPages` array does not contain the final page! This differs from the how the second page functions, which correctly shows the first page in the `previousPages`

See screenshots here:

## Correct on page 2
<img width="948" alt="second-page-success" src="https://user-images.githubusercontent.com/32300026/135144679-408a96e5-e6b7-40c7-a969-7ca8b035c1ab.png">

## Incorrect on page 12 (second last page)

<img width="948" alt="second-last-page-error" src="https://user-images.githubusercontent.com/32300026/135144763-2e610823-6978-4bad-85b6-b9b1e687ce12.png">

**Comment by bebraw** [comment]
Do you want to send a PR with the fix?

**Comment by mattwaler** [comment]
Closing this out.
